/* 
 * Clarksnut
 *
 * Clarksnut UBL collector
 *
 * OpenAPI spec version: 1.2.0-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SpaceRequestAccessApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class SpaceRequestAccessApiTests
    {
        private SpaceRequestAccessApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new SpaceRequestAccessApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SpaceRequestAccessApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' SpaceRequestAccessApi
            //Assert.IsInstanceOfType(typeof(SpaceRequestAccessApi), instance, "instance is a SpaceRequestAccessApi");
        }

        
        /// <summary>
        /// Test GetRequestAccess
        /// </summary>
        [Test]
        public void GetRequestAccessTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetRequestAccess();
            //Assert.IsInstanceOf<GenericDataRepresentationListRequestData> (response, "response is GenericDataRepresentationListRequestData");
        }
        
        /// <summary>
        /// Test RequestAccessToSpace
        /// </summary>
        [Test]
        public void RequestAccessToSpaceTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RequestRepresentation body = null;
            //instance.RequestAccessToSpace(body);
            
        }
        
        /// <summary>
        /// Test UpdateAccessSpace
        /// </summary>
        [Test]
        public void UpdateAccessSpaceTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string requestId = null;
            //RequestRepresentation body = null;
            //instance.UpdateAccessSpace(requestId, body);
            
        }
        
    }

}
