/* 
 * Clarksnut
 *
 * Clarksnut UBL collector
 *
 * OpenAPI spec version: 1.2.0-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// NotificationsAttributes
    /// </summary>
    [DataContract]
    public partial class NotificationsAttributes :  IEquatable<NotificationsAttributes>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NotificationsAttributes" /> class.
        /// </summary>
        /// <param name="RequestAccesses">RequestAccesses.</param>
        public NotificationsAttributes(List<RequestData> RequestAccesses = default(List<RequestData>))
        {
            this.RequestAccesses = RequestAccesses;
        }
        
        /// <summary>
        /// Gets or Sets RequestAccesses
        /// </summary>
        [DataMember(Name="requestAccesses", EmitDefaultValue=false)]
        public List<RequestData> RequestAccesses { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class NotificationsAttributes {\n");
            sb.Append("  RequestAccesses: ").Append(RequestAccesses).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as NotificationsAttributes);
        }

        /// <summary>
        /// Returns true if NotificationsAttributes instances are equal
        /// </summary>
        /// <param name="input">Instance of NotificationsAttributes to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(NotificationsAttributes input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.RequestAccesses == input.RequestAccesses ||
                    this.RequestAccesses != null &&
                    this.RequestAccesses.SequenceEqual(input.RequestAccesses)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.RequestAccesses != null)
                    hashCode = hashCode * 59 + this.RequestAccesses.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
