/* 
 * Clarksnut
 *
 * Clarksnut UBL collector
 *
 * OpenAPI spec version: 1.2.0-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// SpaceRelationships
    /// </summary>
    [DataContract]
    public partial class SpaceRelationships :  IEquatable<SpaceRelationships>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SpaceRelationships" /> class.
        /// </summary>
        /// <param name="OwnedBy">OwnedBy.</param>
        /// <param name="Collaborators">Collaborators.</param>
        public SpaceRelationships(SpaceOwnedBy OwnedBy = default(SpaceOwnedBy), SpaceCollaborators Collaborators = default(SpaceCollaborators))
        {
            this.OwnedBy = OwnedBy;
            this.Collaborators = Collaborators;
        }
        
        /// <summary>
        /// Gets or Sets OwnedBy
        /// </summary>
        [DataMember(Name="ownedBy", EmitDefaultValue=false)]
        public SpaceOwnedBy OwnedBy { get; set; }

        /// <summary>
        /// Gets or Sets Collaborators
        /// </summary>
        [DataMember(Name="collaborators", EmitDefaultValue=false)]
        public SpaceCollaborators Collaborators { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SpaceRelationships {\n");
            sb.Append("  OwnedBy: ").Append(OwnedBy).Append("\n");
            sb.Append("  Collaborators: ").Append(Collaborators).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SpaceRelationships);
        }

        /// <summary>
        /// Returns true if SpaceRelationships instances are equal
        /// </summary>
        /// <param name="input">Instance of SpaceRelationships to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SpaceRelationships input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.OwnedBy == input.OwnedBy ||
                    (this.OwnedBy != null &&
                    this.OwnedBy.Equals(input.OwnedBy))
                ) && 
                (
                    this.Collaborators == input.Collaborators ||
                    (this.Collaborators != null &&
                    this.Collaborators.Equals(input.Collaborators))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.OwnedBy != null)
                    hashCode = hashCode * 59 + this.OwnedBy.GetHashCode();
                if (this.Collaborators != null)
                    hashCode = hashCode * 59 + this.Collaborators.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
