/* 
 * Clarksnut
 *
 * Clarksnut UBL collector
 *
 * OpenAPI spec version: 1.2.0-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DocumentQueryAttributes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DocumentQueryAttributesTests
    {
        // TODO uncomment below to declare an instance variable for DocumentQueryAttributes
        //private DocumentQueryAttributes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DocumentQueryAttributes
            //instance = new DocumentQueryAttributes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DocumentQueryAttributes
        /// </summary>
        [Test]
        public void DocumentQueryAttributesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DocumentQueryAttributes
            //Assert.IsInstanceOfType<DocumentQueryAttributes> (instance, "variable 'instance' is a DocumentQueryAttributes");
        }


        /// <summary>
        /// Test the property 'Role'
        /// </summary>
        [Test]
        public void RoleTest()
        {
            // TODO unit test for the property 'Role'
        }
        /// <summary>
        /// Test the property 'FilterText'
        /// </summary>
        [Test]
        public void FilterTextTest()
        {
            // TODO unit test for the property 'FilterText'
        }
        /// <summary>
        /// Test the property 'Types'
        /// </summary>
        [Test]
        public void TypesTest()
        {
            // TODO unit test for the property 'Types'
        }
        /// <summary>
        /// Test the property 'Currencies'
        /// </summary>
        [Test]
        public void CurrenciesTest()
        {
            // TODO unit test for the property 'Currencies'
        }
        /// <summary>
        /// Test the property 'After'
        /// </summary>
        [Test]
        public void AfterTest()
        {
            // TODO unit test for the property 'After'
        }
        /// <summary>
        /// Test the property 'Before'
        /// </summary>
        [Test]
        public void BeforeTest()
        {
            // TODO unit test for the property 'Before'
        }
        /// <summary>
        /// Test the property 'LessThan'
        /// </summary>
        [Test]
        public void LessThanTest()
        {
            // TODO unit test for the property 'LessThan'
        }
        /// <summary>
        /// Test the property 'GreaterThan'
        /// </summary>
        [Test]
        public void GreaterThanTest()
        {
            // TODO unit test for the property 'GreaterThan'
        }
        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Test]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }
        /// <summary>
        /// Test the property 'Spaces'
        /// </summary>
        [Test]
        public void SpacesTest()
        {
            // TODO unit test for the property 'Spaces'
        }
        /// <summary>
        /// Test the property 'OrderBy'
        /// </summary>
        [Test]
        public void OrderByTest()
        {
            // TODO unit test for the property 'OrderBy'
        }
        /// <summary>
        /// Test the property 'Asc'
        /// </summary>
        [Test]
        public void AscTest()
        {
            // TODO unit test for the property 'Asc'
        }
        /// <summary>
        /// Test the property 'Offset'
        /// </summary>
        [Test]
        public void OffsetTest()
        {
            // TODO unit test for the property 'Offset'
        }
        /// <summary>
        /// Test the property 'Limit'
        /// </summary>
        [Test]
        public void LimitTest()
        {
            // TODO unit test for the property 'Limit'
        }
        /// <summary>
        /// Test the property 'Starred'
        /// </summary>
        [Test]
        public void StarredTest()
        {
            // TODO unit test for the property 'Starred'
        }
        /// <summary>
        /// Test the property 'Viewed'
        /// </summary>
        [Test]
        public void ViewedTest()
        {
            // TODO unit test for the property 'Viewed'
        }
        /// <summary>
        /// Test the property '_Checked'
        /// </summary>
        [Test]
        public void _CheckedTest()
        {
            // TODO unit test for the property '_Checked'
        }

    }

}
