/* 
 * Clarksnut
 *
 * Clarksnut UBL collector
 *
 * OpenAPI spec version: 1.2.0-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DocumentAttributes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DocumentAttributesTests
    {
        // TODO uncomment below to declare an instance variable for DocumentAttributes
        //private DocumentAttributes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DocumentAttributes
            //instance = new DocumentAttributes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DocumentAttributes
        /// </summary>
        [Test]
        public void DocumentAttributesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DocumentAttributes
            //Assert.IsInstanceOfType<DocumentAttributes> (instance, "variable 'instance' is a DocumentAttributes");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'AssignedId'
        /// </summary>
        [Test]
        public void AssignedIdTest()
        {
            // TODO unit test for the property 'AssignedId'
        }
        /// <summary>
        /// Test the property 'SupplierAssignedId'
        /// </summary>
        [Test]
        public void SupplierAssignedIdTest()
        {
            // TODO unit test for the property 'SupplierAssignedId'
        }
        /// <summary>
        /// Test the property 'CustomerAssignedId'
        /// </summary>
        [Test]
        public void CustomerAssignedIdTest()
        {
            // TODO unit test for the property 'CustomerAssignedId'
        }
        /// <summary>
        /// Test the property 'IssueDate'
        /// </summary>
        [Test]
        public void IssueDateTest()
        {
            // TODO unit test for the property 'IssueDate'
        }
        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Test]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Test]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'Tax'
        /// </summary>
        [Test]
        public void TaxTest()
        {
            // TODO unit test for the property 'Tax'
        }
        /// <summary>
        /// Test the property 'SupplierName'
        /// </summary>
        [Test]
        public void SupplierNameTest()
        {
            // TODO unit test for the property 'SupplierName'
        }
        /// <summary>
        /// Test the property 'SupplierStreetAddress'
        /// </summary>
        [Test]
        public void SupplierStreetAddressTest()
        {
            // TODO unit test for the property 'SupplierStreetAddress'
        }
        /// <summary>
        /// Test the property 'SupplierCity'
        /// </summary>
        [Test]
        public void SupplierCityTest()
        {
            // TODO unit test for the property 'SupplierCity'
        }
        /// <summary>
        /// Test the property 'SupplierCountry'
        /// </summary>
        [Test]
        public void SupplierCountryTest()
        {
            // TODO unit test for the property 'SupplierCountry'
        }
        /// <summary>
        /// Test the property 'CustomerName'
        /// </summary>
        [Test]
        public void CustomerNameTest()
        {
            // TODO unit test for the property 'CustomerName'
        }
        /// <summary>
        /// Test the property 'CustomerStreetAddress'
        /// </summary>
        [Test]
        public void CustomerStreetAddressTest()
        {
            // TODO unit test for the property 'CustomerStreetAddress'
        }
        /// <summary>
        /// Test the property 'CustomerCity'
        /// </summary>
        [Test]
        public void CustomerCityTest()
        {
            // TODO unit test for the property 'CustomerCity'
        }
        /// <summary>
        /// Test the property 'CustomerCountry'
        /// </summary>
        [Test]
        public void CustomerCountryTest()
        {
            // TODO unit test for the property 'CustomerCountry'
        }
        /// <summary>
        /// Test the property 'Viewed'
        /// </summary>
        [Test]
        public void ViewedTest()
        {
            // TODO unit test for the property 'Viewed'
        }
        /// <summary>
        /// Test the property 'Starred'
        /// </summary>
        [Test]
        public void StarredTest()
        {
            // TODO unit test for the property 'Starred'
        }
        /// <summary>
        /// Test the property '_Checked'
        /// </summary>
        [Test]
        public void _CheckedTest()
        {
            // TODO unit test for the property '_Checked'
        }
        /// <summary>
        /// Test the property 'Versions'
        /// </summary>
        [Test]
        public void VersionsTest()
        {
            // TODO unit test for the property 'Versions'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Test]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

    }

}
