/* 
 * Clarksnut
 *
 * Clarksnut UBL collector
 *
 * OpenAPI spec version: 1.2.0-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing GenericLinksRepresentation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GenericLinksRepresentationTests
    {
        // TODO uncomment below to declare an instance variable for GenericLinksRepresentation
        //private GenericLinksRepresentation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GenericLinksRepresentation
            //instance = new GenericLinksRepresentation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GenericLinksRepresentation
        /// </summary>
        [Test]
        public void GenericLinksRepresentationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GenericLinksRepresentation
            //Assert.IsInstanceOfType<GenericLinksRepresentation> (instance, "variable 'instance' is a GenericLinksRepresentation");
        }


        /// <summary>
        /// Test the property 'Self'
        /// </summary>
        [Test]
        public void SelfTest()
        {
            // TODO unit test for the property 'Self'
        }
        /// <summary>
        /// Test the property 'Related'
        /// </summary>
        [Test]
        public void RelatedTest()
        {
            // TODO unit test for the property 'Related'
        }
        /// <summary>
        /// Test the property 'Meta'
        /// </summary>
        [Test]
        public void MetaTest()
        {
            // TODO unit test for the property 'Meta'
        }

    }

}
