/* 
 * Clarksnut
 *
 * Clarksnut UBL collector
 *
 * OpenAPI spec version: 1.2.0-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InputPart
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InputPartTests
    {
        // TODO uncomment below to declare an instance variable for InputPart
        //private InputPart instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InputPart
            //instance = new InputPart();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InputPart
        /// </summary>
        [Test]
        public void InputPartInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InputPart
            //Assert.IsInstanceOfType<InputPart> (instance, "variable 'instance' is a InputPart");
        }


        /// <summary>
        /// Test the property 'ContentTypeFromMessage'
        /// </summary>
        [Test]
        public void ContentTypeFromMessageTest()
        {
            // TODO unit test for the property 'ContentTypeFromMessage'
        }
        /// <summary>
        /// Test the property 'BodyAsString'
        /// </summary>
        [Test]
        public void BodyAsStringTest()
        {
            // TODO unit test for the property 'BodyAsString'
        }
        /// <summary>
        /// Test the property 'MediaType'
        /// </summary>
        [Test]
        public void MediaTypeTest()
        {
            // TODO unit test for the property 'MediaType'
        }
        /// <summary>
        /// Test the property 'Headers'
        /// </summary>
        [Test]
        public void HeadersTest()
        {
            // TODO unit test for the property 'Headers'
        }

    }

}
