/* 
 * Clarksnut
 *
 * Clarksnut UBL collector
 *
 * OpenAPI spec version: 1.2.0-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MultipartFormDataInput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MultipartFormDataInputTests
    {
        // TODO uncomment below to declare an instance variable for MultipartFormDataInput
        //private MultipartFormDataInput instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MultipartFormDataInput
            //instance = new MultipartFormDataInput();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MultipartFormDataInput
        /// </summary>
        [Test]
        public void MultipartFormDataInputInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MultipartFormDataInput
            //Assert.IsInstanceOfType<MultipartFormDataInput> (instance, "variable 'instance' is a MultipartFormDataInput");
        }


        /// <summary>
        /// Test the property 'FormDataMap'
        /// </summary>
        [Test]
        public void FormDataMapTest()
        {
            // TODO unit test for the property 'FormDataMap'
        }
        /// <summary>
        /// Test the property 'FormData'
        /// </summary>
        [Test]
        public void FormDataTest()
        {
            // TODO unit test for the property 'FormData'
        }
        /// <summary>
        /// Test the property 'Parts'
        /// </summary>
        [Test]
        public void PartsTest()
        {
            // TODO unit test for the property 'Parts'
        }
        /// <summary>
        /// Test the property 'Preamble'
        /// </summary>
        [Test]
        public void PreambleTest()
        {
            // TODO unit test for the property 'Preamble'
        }

    }

}
