/* 
 * Clarksnut
 *
 * Clarksnut UBL collector
 *
 * OpenAPI spec version: 1.2.0-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing NotificationsAttributes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NotificationsAttributesTests
    {
        // TODO uncomment below to declare an instance variable for NotificationsAttributes
        //private NotificationsAttributes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NotificationsAttributes
            //instance = new NotificationsAttributes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NotificationsAttributes
        /// </summary>
        [Test]
        public void NotificationsAttributesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NotificationsAttributes
            //Assert.IsInstanceOfType<NotificationsAttributes> (instance, "variable 'instance' is a NotificationsAttributes");
        }


        /// <summary>
        /// Test the property 'RequestAccesses'
        /// </summary>
        [Test]
        public void RequestAccessesTest()
        {
            // TODO unit test for the property 'RequestAccesses'
        }

    }

}
