/* 
 * Clarksnut
 *
 * Clarksnut UBL collector
 *
 * OpenAPI spec version: 1.2.0-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing UserAttributesRepresentation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UserAttributesRepresentationTests
    {
        // TODO uncomment below to declare an instance variable for UserAttributesRepresentation
        //private UserAttributesRepresentation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UserAttributesRepresentation
            //instance = new UserAttributesRepresentation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserAttributesRepresentation
        /// </summary>
        [Test]
        public void UserAttributesRepresentationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserAttributesRepresentation
            //Assert.IsInstanceOfType<UserAttributesRepresentation> (instance, "variable 'instance' is a UserAttributesRepresentation");
        }


        /// <summary>
        /// Test the property 'UserID'
        /// </summary>
        [Test]
        public void UserIDTest()
        {
            // TODO unit test for the property 'UserID'
        }
        /// <summary>
        /// Test the property 'FullName'
        /// </summary>
        [Test]
        public void FullNameTest()
        {
            // TODO unit test for the property 'FullName'
        }
        /// <summary>
        /// Test the property 'ImageURL'
        /// </summary>
        [Test]
        public void ImageURLTest()
        {
            // TODO unit test for the property 'ImageURL'
        }
        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Test]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }
        /// <summary>
        /// Test the property 'RegistrationCompleted'
        /// </summary>
        [Test]
        public void RegistrationCompletedTest()
        {
            // TODO unit test for the property 'RegistrationCompleted'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Bio'
        /// </summary>
        [Test]
        public void BioTest()
        {
            // TODO unit test for the property 'Bio'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'Company'
        /// </summary>
        [Test]
        public void CompanyTest()
        {
            // TODO unit test for the property 'Company'
        }
        /// <summary>
        /// Test the property 'ProviderType'
        /// </summary>
        [Test]
        public void ProviderTypeTest()
        {
            // TODO unit test for the property 'ProviderType'
        }
        /// <summary>
        /// Test the property 'DefaultLanguage'
        /// </summary>
        [Test]
        public void DefaultLanguageTest()
        {
            // TODO unit test for the property 'DefaultLanguage'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Test]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

    }

}
