/* 
 * Clarksnut
 *
 * Clarksnut UBL collector
 *
 * OpenAPI spec version: 1.2.0-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface INamedSpacesApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Return allowed Spaces of User
        /// </summary>
        /// <remarks>
        /// [view-users] role required
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">User Id</param>
        /// <param name="role">Role (optional, default to owner)</param>
        /// <param name="offset">First result (optional, default to 0)</param>
        /// <param name="limit">Max results (optional, default to 10)</param>
        /// <returns>GenericDataRepresentationListSpaceData</returns>
        GenericDataRepresentationListSpaceData GetUserSpaces (string userId, string role = null, int? offset = null, int? limit = null);

        /// <summary>
        /// Return allowed Spaces of User
        /// </summary>
        /// <remarks>
        /// [view-users] role required
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">User Id</param>
        /// <param name="role">Role (optional, default to owner)</param>
        /// <param name="offset">First result (optional, default to 0)</param>
        /// <param name="limit">Max results (optional, default to 10)</param>
        /// <returns>ApiResponse of GenericDataRepresentationListSpaceData</returns>
        ApiResponse<GenericDataRepresentationListSpaceData> GetUserSpacesWithHttpInfo (string userId, string role = null, int? offset = null, int? limit = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Return allowed Spaces of User
        /// </summary>
        /// <remarks>
        /// [view-users] role required
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">User Id</param>
        /// <param name="role">Role (optional, default to owner)</param>
        /// <param name="offset">First result (optional, default to 0)</param>
        /// <param name="limit">Max results (optional, default to 10)</param>
        /// <returns>Task of GenericDataRepresentationListSpaceData</returns>
        System.Threading.Tasks.Task<GenericDataRepresentationListSpaceData> GetUserSpacesAsync (string userId, string role = null, int? offset = null, int? limit = null);

        /// <summary>
        /// Return allowed Spaces of User
        /// </summary>
        /// <remarks>
        /// [view-users] role required
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">User Id</param>
        /// <param name="role">Role (optional, default to owner)</param>
        /// <param name="offset">First result (optional, default to 0)</param>
        /// <param name="limit">Max results (optional, default to 10)</param>
        /// <returns>Task of ApiResponse (GenericDataRepresentationListSpaceData)</returns>
        System.Threading.Tasks.Task<ApiResponse<GenericDataRepresentationListSpaceData>> GetUserSpacesAsyncWithHttpInfo (string userId, string role = null, int? offset = null, int? limit = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class NamedSpacesApi : INamedSpacesApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="NamedSpacesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public NamedSpacesApi(String basePath)
        {
            this.Configuration = new Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NamedSpacesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public NamedSpacesApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Return allowed Spaces of User [view-users] role required
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">User Id</param>
        /// <param name="role">Role (optional, default to owner)</param>
        /// <param name="offset">First result (optional, default to 0)</param>
        /// <param name="limit">Max results (optional, default to 10)</param>
        /// <returns>GenericDataRepresentationListSpaceData</returns>
        public GenericDataRepresentationListSpaceData GetUserSpaces (string userId, string role = null, int? offset = null, int? limit = null)
        {
             ApiResponse<GenericDataRepresentationListSpaceData> localVarResponse = GetUserSpacesWithHttpInfo(userId, role, offset, limit);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Return allowed Spaces of User [view-users] role required
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">User Id</param>
        /// <param name="role">Role (optional, default to owner)</param>
        /// <param name="offset">First result (optional, default to 0)</param>
        /// <param name="limit">Max results (optional, default to 10)</param>
        /// <returns>ApiResponse of GenericDataRepresentationListSpaceData</returns>
        public ApiResponse< GenericDataRepresentationListSpaceData > GetUserSpacesWithHttpInfo (string userId, string role = null, int? offset = null, int? limit = null)
        {
            // verify the required parameter 'userId' is set
            if (userId == null)
                throw new ApiException(400, "Missing required parameter 'userId' when calling NamedSpacesApi->GetUserSpaces");

            var localVarPath = "/api/namedspaces/{userId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (userId != null) localVarPathParams.Add("userId", Configuration.ApiClient.ParameterToString(userId)); // path parameter
            if (role != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "role", role)); // query parameter
            if (offset != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "offset", offset)); // query parameter
            if (limit != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "limit", limit)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetUserSpaces", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GenericDataRepresentationListSpaceData>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (GenericDataRepresentationListSpaceData) Configuration.ApiClient.Deserialize(localVarResponse, typeof(GenericDataRepresentationListSpaceData)));
        }

        /// <summary>
        /// Return allowed Spaces of User [view-users] role required
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">User Id</param>
        /// <param name="role">Role (optional, default to owner)</param>
        /// <param name="offset">First result (optional, default to 0)</param>
        /// <param name="limit">Max results (optional, default to 10)</param>
        /// <returns>Task of GenericDataRepresentationListSpaceData</returns>
        public async System.Threading.Tasks.Task<GenericDataRepresentationListSpaceData> GetUserSpacesAsync (string userId, string role = null, int? offset = null, int? limit = null)
        {
             ApiResponse<GenericDataRepresentationListSpaceData> localVarResponse = await GetUserSpacesAsyncWithHttpInfo(userId, role, offset, limit);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Return allowed Spaces of User [view-users] role required
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">User Id</param>
        /// <param name="role">Role (optional, default to owner)</param>
        /// <param name="offset">First result (optional, default to 0)</param>
        /// <param name="limit">Max results (optional, default to 10)</param>
        /// <returns>Task of ApiResponse (GenericDataRepresentationListSpaceData)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<GenericDataRepresentationListSpaceData>> GetUserSpacesAsyncWithHttpInfo (string userId, string role = null, int? offset = null, int? limit = null)
        {
            // verify the required parameter 'userId' is set
            if (userId == null)
                throw new ApiException(400, "Missing required parameter 'userId' when calling NamedSpacesApi->GetUserSpaces");

            var localVarPath = "/api/namedspaces/{userId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (userId != null) localVarPathParams.Add("userId", Configuration.ApiClient.ParameterToString(userId)); // path parameter
            if (role != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "role", role)); // query parameter
            if (offset != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "offset", offset)); // query parameter
            if (limit != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "limit", limit)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetUserSpaces", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GenericDataRepresentationListSpaceData>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (GenericDataRepresentationListSpaceData) Configuration.ApiClient.Deserialize(localVarResponse, typeof(GenericDataRepresentationListSpaceData)));
        }

    }
}
