/* 
 * Clarksnut
 *
 * Clarksnut UBL collector
 *
 * OpenAPI spec version: 1.2.0-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISpacesApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Add new Collaborator
        /// </summary>
        /// <remarks>
        /// [user] role required
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <param name="body"> (optional)</param>
        /// <returns></returns>
        void AddSpaceCollaborators (string spaceId, TypedGenericDataRepresentationListUserData body = null);

        /// <summary>
        /// Add new Collaborator
        /// </summary>
        /// <remarks>
        /// [user] role required
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> AddSpaceCollaboratorsWithHttpInfo (string spaceId, TypedGenericDataRepresentationListUserData body = null);
        /// <summary>
        /// Create new Space
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns></returns>
        void CreateSpace (SpaceRepresentation body = null);

        /// <summary>
        /// Create new Space
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> CreateSpaceWithHttpInfo (SpaceRepresentation body = null);
        /// <summary>
        /// Delete space
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <returns></returns>
        void DeleteUserSpace (string spaceId);

        /// <summary>
        /// Delete space
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> DeleteUserSpaceWithHttpInfo (string spaceId);
        /// <summary>
        /// Return one Space
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <returns>SpaceRepresentation</returns>
        SpaceRepresentation GetSpace (string spaceId);

        /// <summary>
        /// Return one Space
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <returns>ApiResponse of SpaceRepresentation</returns>
        ApiResponse<SpaceRepresentation> GetSpaceWithHttpInfo (string spaceId);
        /// <summary>
        /// Return list of Collaborators
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <param name="offset">First result (optional, default to 0)</param>
        /// <param name="limit">Max results (optional, default to 10)</param>
        /// <returns>GenericDataRepresentationListUserData</returns>
        GenericDataRepresentationListUserData GetSpaceCollaborators (string spaceId, int? offset = null, int? limit = null);

        /// <summary>
        /// Return list of Collaborators
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <param name="offset">First result (optional, default to 0)</param>
        /// <param name="limit">Max results (optional, default to 10)</param>
        /// <returns>ApiResponse of GenericDataRepresentationListUserData</returns>
        ApiResponse<GenericDataRepresentationListUserData> GetSpaceCollaboratorsWithHttpInfo (string spaceId, int? offset = null, int? limit = null);
        /// <summary>
        /// Return list of Spaces
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assignedId">Space Assigned Id (optional)</param>
        /// <param name="filterText">Filter Text (optional)</param>
        /// <param name="offset">First result (optional, default to 0)</param>
        /// <param name="limit">Max results (optional, default to 10)</param>
        /// <returns>GenericDataRepresentationListSpaceData</returns>
        GenericDataRepresentationListSpaceData GetSpaces (string assignedId = null, string filterText = null, int? offset = null, int? limit = null);

        /// <summary>
        /// Return list of Spaces
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assignedId">Space Assigned Id (optional)</param>
        /// <param name="filterText">Filter Text (optional)</param>
        /// <param name="offset">First result (optional, default to 0)</param>
        /// <param name="limit">Max results (optional, default to 10)</param>
        /// <returns>ApiResponse of GenericDataRepresentationListSpaceData</returns>
        ApiResponse<GenericDataRepresentationListSpaceData> GetSpacesWithHttpInfo (string assignedId = null, string filterText = null, int? offset = null, int? limit = null);
        /// <summary>
        /// Remove Collaborator
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <param name="userId">User Id</param>
        /// <returns></returns>
        void RemoveSpaceCollaborators (string spaceId, string userId);

        /// <summary>
        /// Remove Collaborator
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <param name="userId">User Id</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> RemoveSpaceCollaboratorsWithHttpInfo (string spaceId, string userId);
        /// <summary>
        /// Update space
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <param name="body"> (optional)</param>
        /// <returns>SpaceRepresentation</returns>
        SpaceRepresentation UpdateUserSpace (string spaceId, SpaceRepresentation body = null);

        /// <summary>
        /// Update space
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of SpaceRepresentation</returns>
        ApiResponse<SpaceRepresentation> UpdateUserSpaceWithHttpInfo (string spaceId, SpaceRepresentation body = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Add new Collaborator
        /// </summary>
        /// <remarks>
        /// [user] role required
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task AddSpaceCollaboratorsAsync (string spaceId, TypedGenericDataRepresentationListUserData body = null);

        /// <summary>
        /// Add new Collaborator
        /// </summary>
        /// <remarks>
        /// [user] role required
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> AddSpaceCollaboratorsAsyncWithHttpInfo (string spaceId, TypedGenericDataRepresentationListUserData body = null);
        /// <summary>
        /// Create new Space
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task CreateSpaceAsync (SpaceRepresentation body = null);

        /// <summary>
        /// Create new Space
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> CreateSpaceAsyncWithHttpInfo (SpaceRepresentation body = null);
        /// <summary>
        /// Delete space
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task DeleteUserSpaceAsync (string spaceId);

        /// <summary>
        /// Delete space
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DeleteUserSpaceAsyncWithHttpInfo (string spaceId);
        /// <summary>
        /// Return one Space
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <returns>Task of SpaceRepresentation</returns>
        System.Threading.Tasks.Task<SpaceRepresentation> GetSpaceAsync (string spaceId);

        /// <summary>
        /// Return one Space
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <returns>Task of ApiResponse (SpaceRepresentation)</returns>
        System.Threading.Tasks.Task<ApiResponse<SpaceRepresentation>> GetSpaceAsyncWithHttpInfo (string spaceId);
        /// <summary>
        /// Return list of Collaborators
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <param name="offset">First result (optional, default to 0)</param>
        /// <param name="limit">Max results (optional, default to 10)</param>
        /// <returns>Task of GenericDataRepresentationListUserData</returns>
        System.Threading.Tasks.Task<GenericDataRepresentationListUserData> GetSpaceCollaboratorsAsync (string spaceId, int? offset = null, int? limit = null);

        /// <summary>
        /// Return list of Collaborators
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <param name="offset">First result (optional, default to 0)</param>
        /// <param name="limit">Max results (optional, default to 10)</param>
        /// <returns>Task of ApiResponse (GenericDataRepresentationListUserData)</returns>
        System.Threading.Tasks.Task<ApiResponse<GenericDataRepresentationListUserData>> GetSpaceCollaboratorsAsyncWithHttpInfo (string spaceId, int? offset = null, int? limit = null);
        /// <summary>
        /// Return list of Spaces
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assignedId">Space Assigned Id (optional)</param>
        /// <param name="filterText">Filter Text (optional)</param>
        /// <param name="offset">First result (optional, default to 0)</param>
        /// <param name="limit">Max results (optional, default to 10)</param>
        /// <returns>Task of GenericDataRepresentationListSpaceData</returns>
        System.Threading.Tasks.Task<GenericDataRepresentationListSpaceData> GetSpacesAsync (string assignedId = null, string filterText = null, int? offset = null, int? limit = null);

        /// <summary>
        /// Return list of Spaces
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assignedId">Space Assigned Id (optional)</param>
        /// <param name="filterText">Filter Text (optional)</param>
        /// <param name="offset">First result (optional, default to 0)</param>
        /// <param name="limit">Max results (optional, default to 10)</param>
        /// <returns>Task of ApiResponse (GenericDataRepresentationListSpaceData)</returns>
        System.Threading.Tasks.Task<ApiResponse<GenericDataRepresentationListSpaceData>> GetSpacesAsyncWithHttpInfo (string assignedId = null, string filterText = null, int? offset = null, int? limit = null);
        /// <summary>
        /// Remove Collaborator
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <param name="userId">User Id</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task RemoveSpaceCollaboratorsAsync (string spaceId, string userId);

        /// <summary>
        /// Remove Collaborator
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <param name="userId">User Id</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> RemoveSpaceCollaboratorsAsyncWithHttpInfo (string spaceId, string userId);
        /// <summary>
        /// Update space
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of SpaceRepresentation</returns>
        System.Threading.Tasks.Task<SpaceRepresentation> UpdateUserSpaceAsync (string spaceId, SpaceRepresentation body = null);

        /// <summary>
        /// Update space
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse (SpaceRepresentation)</returns>
        System.Threading.Tasks.Task<ApiResponse<SpaceRepresentation>> UpdateUserSpaceAsyncWithHttpInfo (string spaceId, SpaceRepresentation body = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class SpacesApi : ISpacesApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="SpacesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SpacesApi(String basePath)
        {
            this.Configuration = new Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SpacesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public SpacesApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Add new Collaborator [user] role required
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <param name="body"> (optional)</param>
        /// <returns></returns>
        public void AddSpaceCollaborators (string spaceId, TypedGenericDataRepresentationListUserData body = null)
        {
             AddSpaceCollaboratorsWithHttpInfo(spaceId, body);
        }

        /// <summary>
        /// Add new Collaborator [user] role required
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> AddSpaceCollaboratorsWithHttpInfo (string spaceId, TypedGenericDataRepresentationListUserData body = null)
        {
            // verify the required parameter 'spaceId' is set
            if (spaceId == null)
                throw new ApiException(400, "Missing required parameter 'spaceId' when calling SpacesApi->AddSpaceCollaborators");

            var localVarPath = "/api/spaces/{spaceId}/collaborators";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (spaceId != null) localVarPathParams.Add("spaceId", Configuration.ApiClient.ParameterToString(spaceId)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AddSpaceCollaborators", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Add new Collaborator [user] role required
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task AddSpaceCollaboratorsAsync (string spaceId, TypedGenericDataRepresentationListUserData body = null)
        {
             await AddSpaceCollaboratorsAsyncWithHttpInfo(spaceId, body);

        }

        /// <summary>
        /// Add new Collaborator [user] role required
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> AddSpaceCollaboratorsAsyncWithHttpInfo (string spaceId, TypedGenericDataRepresentationListUserData body = null)
        {
            // verify the required parameter 'spaceId' is set
            if (spaceId == null)
                throw new ApiException(400, "Missing required parameter 'spaceId' when calling SpacesApi->AddSpaceCollaborators");

            var localVarPath = "/api/spaces/{spaceId}/collaborators";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (spaceId != null) localVarPathParams.Add("spaceId", Configuration.ApiClient.ParameterToString(spaceId)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AddSpaceCollaborators", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Create new Space 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns></returns>
        public void CreateSpace (SpaceRepresentation body = null)
        {
             CreateSpaceWithHttpInfo(body);
        }

        /// <summary>
        /// Create new Space 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> CreateSpaceWithHttpInfo (SpaceRepresentation body = null)
        {

            var localVarPath = "/api/spaces";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateSpace", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Create new Space 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task CreateSpaceAsync (SpaceRepresentation body = null)
        {
             await CreateSpaceAsyncWithHttpInfo(body);

        }

        /// <summary>
        /// Create new Space 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> CreateSpaceAsyncWithHttpInfo (SpaceRepresentation body = null)
        {

            var localVarPath = "/api/spaces";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateSpace", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Delete space 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <returns></returns>
        public void DeleteUserSpace (string spaceId)
        {
             DeleteUserSpaceWithHttpInfo(spaceId);
        }

        /// <summary>
        /// Delete space 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> DeleteUserSpaceWithHttpInfo (string spaceId)
        {
            // verify the required parameter 'spaceId' is set
            if (spaceId == null)
                throw new ApiException(400, "Missing required parameter 'spaceId' when calling SpacesApi->DeleteUserSpace");

            var localVarPath = "/api/spaces/{spaceId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (spaceId != null) localVarPathParams.Add("spaceId", Configuration.ApiClient.ParameterToString(spaceId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteUserSpace", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Delete space 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task DeleteUserSpaceAsync (string spaceId)
        {
             await DeleteUserSpaceAsyncWithHttpInfo(spaceId);

        }

        /// <summary>
        /// Delete space 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> DeleteUserSpaceAsyncWithHttpInfo (string spaceId)
        {
            // verify the required parameter 'spaceId' is set
            if (spaceId == null)
                throw new ApiException(400, "Missing required parameter 'spaceId' when calling SpacesApi->DeleteUserSpace");

            var localVarPath = "/api/spaces/{spaceId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (spaceId != null) localVarPathParams.Add("spaceId", Configuration.ApiClient.ParameterToString(spaceId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteUserSpace", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Return one Space 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <returns>SpaceRepresentation</returns>
        public SpaceRepresentation GetSpace (string spaceId)
        {
             ApiResponse<SpaceRepresentation> localVarResponse = GetSpaceWithHttpInfo(spaceId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Return one Space 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <returns>ApiResponse of SpaceRepresentation</returns>
        public ApiResponse< SpaceRepresentation > GetSpaceWithHttpInfo (string spaceId)
        {
            // verify the required parameter 'spaceId' is set
            if (spaceId == null)
                throw new ApiException(400, "Missing required parameter 'spaceId' when calling SpacesApi->GetSpace");

            var localVarPath = "/api/spaces/{spaceId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (spaceId != null) localVarPathParams.Add("spaceId", Configuration.ApiClient.ParameterToString(spaceId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetSpace", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SpaceRepresentation>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (SpaceRepresentation) Configuration.ApiClient.Deserialize(localVarResponse, typeof(SpaceRepresentation)));
        }

        /// <summary>
        /// Return one Space 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <returns>Task of SpaceRepresentation</returns>
        public async System.Threading.Tasks.Task<SpaceRepresentation> GetSpaceAsync (string spaceId)
        {
             ApiResponse<SpaceRepresentation> localVarResponse = await GetSpaceAsyncWithHttpInfo(spaceId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Return one Space 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <returns>Task of ApiResponse (SpaceRepresentation)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<SpaceRepresentation>> GetSpaceAsyncWithHttpInfo (string spaceId)
        {
            // verify the required parameter 'spaceId' is set
            if (spaceId == null)
                throw new ApiException(400, "Missing required parameter 'spaceId' when calling SpacesApi->GetSpace");

            var localVarPath = "/api/spaces/{spaceId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (spaceId != null) localVarPathParams.Add("spaceId", Configuration.ApiClient.ParameterToString(spaceId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetSpace", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SpaceRepresentation>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (SpaceRepresentation) Configuration.ApiClient.Deserialize(localVarResponse, typeof(SpaceRepresentation)));
        }

        /// <summary>
        /// Return list of Collaborators 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <param name="offset">First result (optional, default to 0)</param>
        /// <param name="limit">Max results (optional, default to 10)</param>
        /// <returns>GenericDataRepresentationListUserData</returns>
        public GenericDataRepresentationListUserData GetSpaceCollaborators (string spaceId, int? offset = null, int? limit = null)
        {
             ApiResponse<GenericDataRepresentationListUserData> localVarResponse = GetSpaceCollaboratorsWithHttpInfo(spaceId, offset, limit);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Return list of Collaborators 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <param name="offset">First result (optional, default to 0)</param>
        /// <param name="limit">Max results (optional, default to 10)</param>
        /// <returns>ApiResponse of GenericDataRepresentationListUserData</returns>
        public ApiResponse< GenericDataRepresentationListUserData > GetSpaceCollaboratorsWithHttpInfo (string spaceId, int? offset = null, int? limit = null)
        {
            // verify the required parameter 'spaceId' is set
            if (spaceId == null)
                throw new ApiException(400, "Missing required parameter 'spaceId' when calling SpacesApi->GetSpaceCollaborators");

            var localVarPath = "/api/spaces/{spaceId}/collaborators";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (spaceId != null) localVarPathParams.Add("spaceId", Configuration.ApiClient.ParameterToString(spaceId)); // path parameter
            if (offset != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "offset", offset)); // query parameter
            if (limit != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "limit", limit)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetSpaceCollaborators", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GenericDataRepresentationListUserData>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (GenericDataRepresentationListUserData) Configuration.ApiClient.Deserialize(localVarResponse, typeof(GenericDataRepresentationListUserData)));
        }

        /// <summary>
        /// Return list of Collaborators 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <param name="offset">First result (optional, default to 0)</param>
        /// <param name="limit">Max results (optional, default to 10)</param>
        /// <returns>Task of GenericDataRepresentationListUserData</returns>
        public async System.Threading.Tasks.Task<GenericDataRepresentationListUserData> GetSpaceCollaboratorsAsync (string spaceId, int? offset = null, int? limit = null)
        {
             ApiResponse<GenericDataRepresentationListUserData> localVarResponse = await GetSpaceCollaboratorsAsyncWithHttpInfo(spaceId, offset, limit);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Return list of Collaborators 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <param name="offset">First result (optional, default to 0)</param>
        /// <param name="limit">Max results (optional, default to 10)</param>
        /// <returns>Task of ApiResponse (GenericDataRepresentationListUserData)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<GenericDataRepresentationListUserData>> GetSpaceCollaboratorsAsyncWithHttpInfo (string spaceId, int? offset = null, int? limit = null)
        {
            // verify the required parameter 'spaceId' is set
            if (spaceId == null)
                throw new ApiException(400, "Missing required parameter 'spaceId' when calling SpacesApi->GetSpaceCollaborators");

            var localVarPath = "/api/spaces/{spaceId}/collaborators";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (spaceId != null) localVarPathParams.Add("spaceId", Configuration.ApiClient.ParameterToString(spaceId)); // path parameter
            if (offset != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "offset", offset)); // query parameter
            if (limit != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "limit", limit)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetSpaceCollaborators", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GenericDataRepresentationListUserData>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (GenericDataRepresentationListUserData) Configuration.ApiClient.Deserialize(localVarResponse, typeof(GenericDataRepresentationListUserData)));
        }

        /// <summary>
        /// Return list of Spaces 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assignedId">Space Assigned Id (optional)</param>
        /// <param name="filterText">Filter Text (optional)</param>
        /// <param name="offset">First result (optional, default to 0)</param>
        /// <param name="limit">Max results (optional, default to 10)</param>
        /// <returns>GenericDataRepresentationListSpaceData</returns>
        public GenericDataRepresentationListSpaceData GetSpaces (string assignedId = null, string filterText = null, int? offset = null, int? limit = null)
        {
             ApiResponse<GenericDataRepresentationListSpaceData> localVarResponse = GetSpacesWithHttpInfo(assignedId, filterText, offset, limit);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Return list of Spaces 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assignedId">Space Assigned Id (optional)</param>
        /// <param name="filterText">Filter Text (optional)</param>
        /// <param name="offset">First result (optional, default to 0)</param>
        /// <param name="limit">Max results (optional, default to 10)</param>
        /// <returns>ApiResponse of GenericDataRepresentationListSpaceData</returns>
        public ApiResponse< GenericDataRepresentationListSpaceData > GetSpacesWithHttpInfo (string assignedId = null, string filterText = null, int? offset = null, int? limit = null)
        {

            var localVarPath = "/api/spaces";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (assignedId != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "assignedId", assignedId)); // query parameter
            if (filterText != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "filterText", filterText)); // query parameter
            if (offset != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "offset", offset)); // query parameter
            if (limit != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "limit", limit)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetSpaces", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GenericDataRepresentationListSpaceData>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (GenericDataRepresentationListSpaceData) Configuration.ApiClient.Deserialize(localVarResponse, typeof(GenericDataRepresentationListSpaceData)));
        }

        /// <summary>
        /// Return list of Spaces 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assignedId">Space Assigned Id (optional)</param>
        /// <param name="filterText">Filter Text (optional)</param>
        /// <param name="offset">First result (optional, default to 0)</param>
        /// <param name="limit">Max results (optional, default to 10)</param>
        /// <returns>Task of GenericDataRepresentationListSpaceData</returns>
        public async System.Threading.Tasks.Task<GenericDataRepresentationListSpaceData> GetSpacesAsync (string assignedId = null, string filterText = null, int? offset = null, int? limit = null)
        {
             ApiResponse<GenericDataRepresentationListSpaceData> localVarResponse = await GetSpacesAsyncWithHttpInfo(assignedId, filterText, offset, limit);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Return list of Spaces 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assignedId">Space Assigned Id (optional)</param>
        /// <param name="filterText">Filter Text (optional)</param>
        /// <param name="offset">First result (optional, default to 0)</param>
        /// <param name="limit">Max results (optional, default to 10)</param>
        /// <returns>Task of ApiResponse (GenericDataRepresentationListSpaceData)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<GenericDataRepresentationListSpaceData>> GetSpacesAsyncWithHttpInfo (string assignedId = null, string filterText = null, int? offset = null, int? limit = null)
        {

            var localVarPath = "/api/spaces";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (assignedId != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "assignedId", assignedId)); // query parameter
            if (filterText != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "filterText", filterText)); // query parameter
            if (offset != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "offset", offset)); // query parameter
            if (limit != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "limit", limit)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetSpaces", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GenericDataRepresentationListSpaceData>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (GenericDataRepresentationListSpaceData) Configuration.ApiClient.Deserialize(localVarResponse, typeof(GenericDataRepresentationListSpaceData)));
        }

        /// <summary>
        /// Remove Collaborator 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <param name="userId">User Id</param>
        /// <returns></returns>
        public void RemoveSpaceCollaborators (string spaceId, string userId)
        {
             RemoveSpaceCollaboratorsWithHttpInfo(spaceId, userId);
        }

        /// <summary>
        /// Remove Collaborator 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <param name="userId">User Id</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> RemoveSpaceCollaboratorsWithHttpInfo (string spaceId, string userId)
        {
            // verify the required parameter 'spaceId' is set
            if (spaceId == null)
                throw new ApiException(400, "Missing required parameter 'spaceId' when calling SpacesApi->RemoveSpaceCollaborators");
            // verify the required parameter 'userId' is set
            if (userId == null)
                throw new ApiException(400, "Missing required parameter 'userId' when calling SpacesApi->RemoveSpaceCollaborators");

            var localVarPath = "/api/spaces/{spaceId}/collaborators/{userId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (spaceId != null) localVarPathParams.Add("spaceId", Configuration.ApiClient.ParameterToString(spaceId)); // path parameter
            if (userId != null) localVarPathParams.Add("userId", Configuration.ApiClient.ParameterToString(userId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RemoveSpaceCollaborators", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Remove Collaborator 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <param name="userId">User Id</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task RemoveSpaceCollaboratorsAsync (string spaceId, string userId)
        {
             await RemoveSpaceCollaboratorsAsyncWithHttpInfo(spaceId, userId);

        }

        /// <summary>
        /// Remove Collaborator 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <param name="userId">User Id</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> RemoveSpaceCollaboratorsAsyncWithHttpInfo (string spaceId, string userId)
        {
            // verify the required parameter 'spaceId' is set
            if (spaceId == null)
                throw new ApiException(400, "Missing required parameter 'spaceId' when calling SpacesApi->RemoveSpaceCollaborators");
            // verify the required parameter 'userId' is set
            if (userId == null)
                throw new ApiException(400, "Missing required parameter 'userId' when calling SpacesApi->RemoveSpaceCollaborators");

            var localVarPath = "/api/spaces/{spaceId}/collaborators/{userId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (spaceId != null) localVarPathParams.Add("spaceId", Configuration.ApiClient.ParameterToString(spaceId)); // path parameter
            if (userId != null) localVarPathParams.Add("userId", Configuration.ApiClient.ParameterToString(userId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RemoveSpaceCollaborators", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Update space 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <param name="body"> (optional)</param>
        /// <returns>SpaceRepresentation</returns>
        public SpaceRepresentation UpdateUserSpace (string spaceId, SpaceRepresentation body = null)
        {
             ApiResponse<SpaceRepresentation> localVarResponse = UpdateUserSpaceWithHttpInfo(spaceId, body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Update space 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of SpaceRepresentation</returns>
        public ApiResponse< SpaceRepresentation > UpdateUserSpaceWithHttpInfo (string spaceId, SpaceRepresentation body = null)
        {
            // verify the required parameter 'spaceId' is set
            if (spaceId == null)
                throw new ApiException(400, "Missing required parameter 'spaceId' when calling SpacesApi->UpdateUserSpace");

            var localVarPath = "/api/spaces/{spaceId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (spaceId != null) localVarPathParams.Add("spaceId", Configuration.ApiClient.ParameterToString(spaceId)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UpdateUserSpace", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SpaceRepresentation>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (SpaceRepresentation) Configuration.ApiClient.Deserialize(localVarResponse, typeof(SpaceRepresentation)));
        }

        /// <summary>
        /// Update space 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of SpaceRepresentation</returns>
        public async System.Threading.Tasks.Task<SpaceRepresentation> UpdateUserSpaceAsync (string spaceId, SpaceRepresentation body = null)
        {
             ApiResponse<SpaceRepresentation> localVarResponse = await UpdateUserSpaceAsyncWithHttpInfo(spaceId, body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Update space 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse (SpaceRepresentation)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<SpaceRepresentation>> UpdateUserSpaceAsyncWithHttpInfo (string spaceId, SpaceRepresentation body = null)
        {
            // verify the required parameter 'spaceId' is set
            if (spaceId == null)
                throw new ApiException(400, "Missing required parameter 'spaceId' when calling SpacesApi->UpdateUserSpace");

            var localVarPath = "/api/spaces/{spaceId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (spaceId != null) localVarPathParams.Add("spaceId", Configuration.ApiClient.ParameterToString(spaceId)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UpdateUserSpace", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SpaceRepresentation>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (SpaceRepresentation) Configuration.ApiClient.Deserialize(localVarResponse, typeof(SpaceRepresentation)));
        }

    }
}
