/* 
 * Clarksnut
 *
 * Clarksnut UBL collector
 *
 * OpenAPI spec version: 1.2.0-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISpacesApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create Space
        /// </summary>
        /// <remarks>
        /// This will create a space. [user] role required
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns></returns>
        void CreateSpace (SpaceRepresentation body = null);

        /// <summary>
        /// Create Space
        /// </summary>
        /// <remarks>
        /// This will create a space. [user] role required
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> CreateSpaceWithHttpInfo (SpaceRepresentation body = null);
        /// <summary>
        /// Get Space
        /// </summary>
        /// <remarks>
        /// This will get a space. [view-spaces] role required
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <returns>SpaceRepresentation</returns>
        SpaceRepresentation GetSpace (string spaceId);

        /// <summary>
        /// Get Space
        /// </summary>
        /// <remarks>
        /// This will get a space. [view-spaces] role required
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <returns>ApiResponse of SpaceRepresentation</returns>
        ApiResponse<SpaceRepresentation> GetSpaceWithHttpInfo (string spaceId);
        /// <summary>
        /// Get Spaces
        /// </summary>
        /// <remarks>
        /// This will search spaces. [view-spaces] role required
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assignedId">Space Assigned Id (optional)</param>
        /// <param name="q">Full text search value (optional, default to *)</param>
        /// <param name="offset">First result (optional, default to 0)</param>
        /// <param name="limit">Max results (optional, default to 10)</param>
        /// <returns>GenericDataRepresentationListSpaceData</returns>
        GenericDataRepresentationListSpaceData GetSpaces (string assignedId = null, string q = null, int? offset = null, int? limit = null);

        /// <summary>
        /// Get Spaces
        /// </summary>
        /// <remarks>
        /// This will search spaces. [view-spaces] role required
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assignedId">Space Assigned Id (optional)</param>
        /// <param name="q">Full text search value (optional, default to *)</param>
        /// <param name="offset">First result (optional, default to 0)</param>
        /// <param name="limit">Max results (optional, default to 10)</param>
        /// <returns>ApiResponse of GenericDataRepresentationListSpaceData</returns>
        ApiResponse<GenericDataRepresentationListSpaceData> GetSpacesWithHttpInfo (string assignedId = null, string q = null, int? offset = null, int? limit = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Create Space
        /// </summary>
        /// <remarks>
        /// This will create a space. [user] role required
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task CreateSpaceAsync (SpaceRepresentation body = null);

        /// <summary>
        /// Create Space
        /// </summary>
        /// <remarks>
        /// This will create a space. [user] role required
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> CreateSpaceAsyncWithHttpInfo (SpaceRepresentation body = null);
        /// <summary>
        /// Get Space
        /// </summary>
        /// <remarks>
        /// This will get a space. [view-spaces] role required
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <returns>Task of SpaceRepresentation</returns>
        System.Threading.Tasks.Task<SpaceRepresentation> GetSpaceAsync (string spaceId);

        /// <summary>
        /// Get Space
        /// </summary>
        /// <remarks>
        /// This will get a space. [view-spaces] role required
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <returns>Task of ApiResponse (SpaceRepresentation)</returns>
        System.Threading.Tasks.Task<ApiResponse<SpaceRepresentation>> GetSpaceAsyncWithHttpInfo (string spaceId);
        /// <summary>
        /// Get Spaces
        /// </summary>
        /// <remarks>
        /// This will search spaces. [view-spaces] role required
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assignedId">Space Assigned Id (optional)</param>
        /// <param name="q">Full text search value (optional, default to *)</param>
        /// <param name="offset">First result (optional, default to 0)</param>
        /// <param name="limit">Max results (optional, default to 10)</param>
        /// <returns>Task of GenericDataRepresentationListSpaceData</returns>
        System.Threading.Tasks.Task<GenericDataRepresentationListSpaceData> GetSpacesAsync (string assignedId = null, string q = null, int? offset = null, int? limit = null);

        /// <summary>
        /// Get Spaces
        /// </summary>
        /// <remarks>
        /// This will search spaces. [view-spaces] role required
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assignedId">Space Assigned Id (optional)</param>
        /// <param name="q">Full text search value (optional, default to *)</param>
        /// <param name="offset">First result (optional, default to 0)</param>
        /// <param name="limit">Max results (optional, default to 10)</param>
        /// <returns>Task of ApiResponse (GenericDataRepresentationListSpaceData)</returns>
        System.Threading.Tasks.Task<ApiResponse<GenericDataRepresentationListSpaceData>> GetSpacesAsyncWithHttpInfo (string assignedId = null, string q = null, int? offset = null, int? limit = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class SpacesApi : ISpacesApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="SpacesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SpacesApi(String basePath)
        {
            this.Configuration = new Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SpacesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public SpacesApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Create Space This will create a space. [user] role required
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns></returns>
        public void CreateSpace (SpaceRepresentation body = null)
        {
             CreateSpaceWithHttpInfo(body);
        }

        /// <summary>
        /// Create Space This will create a space. [user] role required
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> CreateSpaceWithHttpInfo (SpaceRepresentation body = null)
        {

            var localVarPath = "/api/spaces";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateSpace", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Create Space This will create a space. [user] role required
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task CreateSpaceAsync (SpaceRepresentation body = null)
        {
             await CreateSpaceAsyncWithHttpInfo(body);

        }

        /// <summary>
        /// Create Space This will create a space. [user] role required
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> CreateSpaceAsyncWithHttpInfo (SpaceRepresentation body = null)
        {

            var localVarPath = "/api/spaces";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateSpace", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Get Space This will get a space. [view-spaces] role required
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <returns>SpaceRepresentation</returns>
        public SpaceRepresentation GetSpace (string spaceId)
        {
             ApiResponse<SpaceRepresentation> localVarResponse = GetSpaceWithHttpInfo(spaceId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get Space This will get a space. [view-spaces] role required
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <returns>ApiResponse of SpaceRepresentation</returns>
        public ApiResponse< SpaceRepresentation > GetSpaceWithHttpInfo (string spaceId)
        {
            // verify the required parameter 'spaceId' is set
            if (spaceId == null)
                throw new ApiException(400, "Missing required parameter 'spaceId' when calling SpacesApi->GetSpace");

            var localVarPath = "/api/spaces/{spaceId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (spaceId != null) localVarPathParams.Add("spaceId", Configuration.ApiClient.ParameterToString(spaceId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetSpace", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SpaceRepresentation>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (SpaceRepresentation) Configuration.ApiClient.Deserialize(localVarResponse, typeof(SpaceRepresentation)));
        }

        /// <summary>
        /// Get Space This will get a space. [view-spaces] role required
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <returns>Task of SpaceRepresentation</returns>
        public async System.Threading.Tasks.Task<SpaceRepresentation> GetSpaceAsync (string spaceId)
        {
             ApiResponse<SpaceRepresentation> localVarResponse = await GetSpaceAsyncWithHttpInfo(spaceId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get Space This will get a space. [view-spaces] role required
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="spaceId">Space Id</param>
        /// <returns>Task of ApiResponse (SpaceRepresentation)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<SpaceRepresentation>> GetSpaceAsyncWithHttpInfo (string spaceId)
        {
            // verify the required parameter 'spaceId' is set
            if (spaceId == null)
                throw new ApiException(400, "Missing required parameter 'spaceId' when calling SpacesApi->GetSpace");

            var localVarPath = "/api/spaces/{spaceId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (spaceId != null) localVarPathParams.Add("spaceId", Configuration.ApiClient.ParameterToString(spaceId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetSpace", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SpaceRepresentation>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (SpaceRepresentation) Configuration.ApiClient.Deserialize(localVarResponse, typeof(SpaceRepresentation)));
        }

        /// <summary>
        /// Get Spaces This will search spaces. [view-spaces] role required
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assignedId">Space Assigned Id (optional)</param>
        /// <param name="q">Full text search value (optional, default to *)</param>
        /// <param name="offset">First result (optional, default to 0)</param>
        /// <param name="limit">Max results (optional, default to 10)</param>
        /// <returns>GenericDataRepresentationListSpaceData</returns>
        public GenericDataRepresentationListSpaceData GetSpaces (string assignedId = null, string q = null, int? offset = null, int? limit = null)
        {
             ApiResponse<GenericDataRepresentationListSpaceData> localVarResponse = GetSpacesWithHttpInfo(assignedId, q, offset, limit);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get Spaces This will search spaces. [view-spaces] role required
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assignedId">Space Assigned Id (optional)</param>
        /// <param name="q">Full text search value (optional, default to *)</param>
        /// <param name="offset">First result (optional, default to 0)</param>
        /// <param name="limit">Max results (optional, default to 10)</param>
        /// <returns>ApiResponse of GenericDataRepresentationListSpaceData</returns>
        public ApiResponse< GenericDataRepresentationListSpaceData > GetSpacesWithHttpInfo (string assignedId = null, string q = null, int? offset = null, int? limit = null)
        {

            var localVarPath = "/api/spaces";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (assignedId != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "assignedId", assignedId)); // query parameter
            if (q != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "q", q)); // query parameter
            if (offset != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "offset", offset)); // query parameter
            if (limit != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "limit", limit)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetSpaces", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GenericDataRepresentationListSpaceData>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (GenericDataRepresentationListSpaceData) Configuration.ApiClient.Deserialize(localVarResponse, typeof(GenericDataRepresentationListSpaceData)));
        }

        /// <summary>
        /// Get Spaces This will search spaces. [view-spaces] role required
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assignedId">Space Assigned Id (optional)</param>
        /// <param name="q">Full text search value (optional, default to *)</param>
        /// <param name="offset">First result (optional, default to 0)</param>
        /// <param name="limit">Max results (optional, default to 10)</param>
        /// <returns>Task of GenericDataRepresentationListSpaceData</returns>
        public async System.Threading.Tasks.Task<GenericDataRepresentationListSpaceData> GetSpacesAsync (string assignedId = null, string q = null, int? offset = null, int? limit = null)
        {
             ApiResponse<GenericDataRepresentationListSpaceData> localVarResponse = await GetSpacesAsyncWithHttpInfo(assignedId, q, offset, limit);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get Spaces This will search spaces. [view-spaces] role required
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assignedId">Space Assigned Id (optional)</param>
        /// <param name="q">Full text search value (optional, default to *)</param>
        /// <param name="offset">First result (optional, default to 0)</param>
        /// <param name="limit">Max results (optional, default to 10)</param>
        /// <returns>Task of ApiResponse (GenericDataRepresentationListSpaceData)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<GenericDataRepresentationListSpaceData>> GetSpacesAsyncWithHttpInfo (string assignedId = null, string q = null, int? offset = null, int? limit = null)
        {

            var localVarPath = "/api/spaces";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (assignedId != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "assignedId", assignedId)); // query parameter
            if (q != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "q", q)); // query parameter
            if (offset != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "offset", offset)); // query parameter
            if (limit != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "limit", limit)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetSpaces", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GenericDataRepresentationListSpaceData>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (GenericDataRepresentationListSpaceData) Configuration.ApiClient.Deserialize(localVarResponse, typeof(GenericDataRepresentationListSpaceData)));
        }

    }
}
